### ISSUE TITLE
 Works on Local Host and did not work on the web

### ISSUE THREAD

**Issue by JMultimidia** [crocodic-studio/crudbooster#889]
On my local server it works perfectly, but after sending the project to the web server, several errors appear as seen in the log. How to solve?

[2017-10-04 12:13:56] production.ERROR: exception 'ErrorException' with message 'mkdir(): No such file or directory' in /home/itatexte/laravel/vendor/crocodicstudio/crudbooster/src/CRUDBoosterServiceProvider.php:99
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'mkdir(): No suc...', '/home/itatexte/...', 99, Array)
#1 /home/itatexte/laravel/vendor/crocodicstudio/crudbooster/src/CRUDBoosterServiceProvider.php(99): mkdir('/home/itatexte/...', 511)
#2 /home/itatexte/laravel/vendor/crocodicstudio/crudbooster/src/CRUDBoosterServiceProvider.php(39): crocodicstudio\crudbooster\CRUDBoosterServiceProvider->symlinkFixed()
#3 [internal function]: crocodicstudio\crudbooster\CRUDBoosterServiceProvider->boot()
#4 /home/itatexte/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(30): call_user_func_array(Array, Array)
#5 /home/itatexte/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /home/itatexte/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#7 /home/itatexte/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#8 /home/itatexte/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(788): Illuminate\Container\Container->call(Array)
#9 /home/itatexte/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(771): Illuminate\Foundation\Application->bootProvider(Object(crocodicstudio\crudbooster\CRUDBoosterServiceProvider))
#10 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(crocodicstudio\crudbooster\CRUDBoosterServiceProvider), 18)
#11 /home/itatexte/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(772): array_walk(Array, Object(Closure))
#12 /home/itatexte/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#13 /home/itatexte/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#14 /home/itatexte/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\Foundation\Application->bootstrapWith(Array)
#15 /home/itatexte/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\Foundation\Http\Kernel->bootstrap()
#16 /home/itatexte/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#17 /home/itatexte/public_html/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#18 {main}

**Comment by imanghafoori1** [comment]
Do you develop on windows ? and deploy on linux ?
